// GENERATED by generate-creatures.js from PokéAPI (Gen 1+2). Do not hand-edit.
const CREATURES = [
 {
  "id": "bulbasaur",
  "pid": 1,
  "name": "Bulbasaur",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "ivysaur"
 },
 {
  "id": "ivysaur",
  "pid": 2,
  "name": "Ivysaur",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "venusaur"
 },
 {
  "id": "venusaur",
  "pid": 3,
  "name": "Venusaur",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "charmander",
  "pid": 4,
  "name": "Charmander",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "charmeleon"
 },
 {
  "id": "charmeleon",
  "pid": 5,
  "name": "Charmeleon",
  "types": [
   "Fire"
  ],
  "rarity": 2,
  "evolvesTo": "charizard"
 },
 {
  "id": "charizard",
  "pid": 6,
  "name": "Charizard",
  "types": [
   "Fire",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "squirtle",
  "pid": 7,
  "name": "Squirtle",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "wartortle"
 },
 {
  "id": "wartortle",
  "pid": 8,
  "name": "Wartortle",
  "types": [
   "Water"
  ],
  "rarity": 2,
  "evolvesTo": "blastoise"
 },
 {
  "id": "blastoise",
  "pid": 9,
  "name": "Blastoise",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "caterpie",
  "pid": 10,
  "name": "Caterpie",
  "types": [
   "Bug"
  ],
  "rarity": 1,
  "evolvesTo": "metapod"
 },
 {
  "id": "metapod",
  "pid": 11,
  "name": "Metapod",
  "types": [
   "Bug"
  ],
  "rarity": 1,
  "evolvesTo": "butterfree"
 },
 {
  "id": "butterfree",
  "pid": 12,
  "name": "Butterfree",
  "types": [
   "Bug",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "weedle",
  "pid": 13,
  "name": "Weedle",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "kakuna"
 },
 {
  "id": "kakuna",
  "pid": 14,
  "name": "Kakuna",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "beedrill"
 },
 {
  "id": "beedrill",
  "pid": 15,
  "name": "Beedrill",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "pidgey",
  "pid": 16,
  "name": "Pidgey",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "pidgeotto"
 },
 {
  "id": "pidgeotto",
  "pid": 17,
  "name": "Pidgeotto",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 2,
  "evolvesTo": "pidgeot"
 },
 {
  "id": "pidgeot",
  "pid": 18,
  "name": "Pidgeot",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "rattata",
  "pid": 19,
  "name": "Rattata",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "raticate"
 },
 {
  "id": "raticate",
  "pid": 20,
  "name": "Raticate",
  "types": [
   "Normal"
  ],
  "rarity": 2
 },
 {
  "id": "spearow",
  "pid": 21,
  "name": "Spearow",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "fearow"
 },
 {
  "id": "fearow",
  "pid": 22,
  "name": "Fearow",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "ekans",
  "pid": 23,
  "name": "Ekans",
  "types": [
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "arbok"
 },
 {
  "id": "arbok",
  "pid": 24,
  "name": "Arbok",
  "types": [
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "pikachu",
  "pid": 25,
  "name": "Pikachu",
  "types": [
   "Electric"
  ],
  "rarity": 2,
  "evolvesTo": "raichu"
 },
 {
  "id": "raichu",
  "pid": 26,
  "name": "Raichu",
  "types": [
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "sandshrew",
  "pid": 27,
  "name": "Sandshrew",
  "types": [
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "sandslash"
 },
 {
  "id": "sandslash",
  "pid": 28,
  "name": "Sandslash",
  "types": [
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "nidoran-f",
  "pid": 29,
  "name": "Nidoran♀",
  "types": [
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "nidorina"
 },
 {
  "id": "nidorina",
  "pid": 30,
  "name": "Nidorina",
  "types": [
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "nidoqueen"
 },
 {
  "id": "nidoqueen",
  "pid": 31,
  "name": "Nidoqueen",
  "types": [
   "Poison",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "nidoran-m",
  "pid": 32,
  "name": "Nidoran♂",
  "types": [
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "nidorino"
 },
 {
  "id": "nidorino",
  "pid": 33,
  "name": "Nidorino",
  "types": [
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "nidoking"
 },
 {
  "id": "nidoking",
  "pid": 34,
  "name": "Nidoking",
  "types": [
   "Poison",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "clefairy",
  "pid": 35,
  "name": "Clefairy",
  "types": [
   "Fairy"
  ],
  "rarity": 2,
  "evolvesTo": "clefable"
 },
 {
  "id": "clefable",
  "pid": 36,
  "name": "Clefable",
  "types": [
   "Fairy"
  ],
  "rarity": 3
 },
 {
  "id": "vulpix",
  "pid": 37,
  "name": "Vulpix",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "ninetales"
 },
 {
  "id": "ninetales",
  "pid": 38,
  "name": "Ninetales",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "jigglypuff",
  "pid": 39,
  "name": "Jigglypuff",
  "types": [
   "Normal",
   "Fairy"
  ],
  "rarity": 2,
  "evolvesTo": "wigglytuff"
 },
 {
  "id": "wigglytuff",
  "pid": 40,
  "name": "Wigglytuff",
  "types": [
   "Normal",
   "Fairy"
  ],
  "rarity": 3
 },
 {
  "id": "zubat",
  "pid": 41,
  "name": "Zubat",
  "types": [
   "Poison",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "golbat"
 },
 {
  "id": "golbat",
  "pid": 42,
  "name": "Golbat",
  "types": [
   "Poison",
   "Flying"
  ],
  "rarity": 3,
  "evolvesTo": "crobat"
 },
 {
  "id": "oddish",
  "pid": 43,
  "name": "Oddish",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "gloom"
 },
 {
  "id": "gloom",
  "pid": 44,
  "name": "Gloom",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "vileplume"
 },
 {
  "id": "vileplume",
  "pid": 45,
  "name": "Vileplume",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "paras",
  "pid": 46,
  "name": "Paras",
  "types": [
   "Bug",
   "Grass"
  ],
  "rarity": 1,
  "evolvesTo": "parasect"
 },
 {
  "id": "parasect",
  "pid": 47,
  "name": "Parasect",
  "types": [
   "Bug",
   "Grass"
  ],
  "rarity": 2
 },
 {
  "id": "venonat",
  "pid": 48,
  "name": "Venonat",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "venomoth"
 },
 {
  "id": "venomoth",
  "pid": 49,
  "name": "Venomoth",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "diglett",
  "pid": 50,
  "name": "Diglett",
  "types": [
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "dugtrio"
 },
 {
  "id": "dugtrio",
  "pid": 51,
  "name": "Dugtrio",
  "types": [
   "Ground"
  ],
  "rarity": 2
 },
 {
  "id": "meowth",
  "pid": 52,
  "name": "Meowth",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "persian"
 },
 {
  "id": "persian",
  "pid": 53,
  "name": "Persian",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "psyduck",
  "pid": 54,
  "name": "Psyduck",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "golduck"
 },
 {
  "id": "golduck",
  "pid": 55,
  "name": "Golduck",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "mankey",
  "pid": 56,
  "name": "Mankey",
  "types": [
   "Fighting"
  ],
  "rarity": 1,
  "evolvesTo": "primeape"
 },
 {
  "id": "primeape",
  "pid": 57,
  "name": "Primeape",
  "types": [
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "growlithe",
  "pid": 58,
  "name": "Growlithe",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "arcanine"
 },
 {
  "id": "arcanine",
  "pid": 59,
  "name": "Arcanine",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "poliwag",
  "pid": 60,
  "name": "Poliwag",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "poliwhirl"
 },
 {
  "id": "poliwhirl",
  "pid": 61,
  "name": "Poliwhirl",
  "types": [
   "Water"
  ],
  "rarity": 2,
  "evolvesTo": "poliwrath"
 },
 {
  "id": "poliwrath",
  "pid": 62,
  "name": "Poliwrath",
  "types": [
   "Water",
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "abra",
  "pid": 63,
  "name": "Abra",
  "types": [
   "Psychic"
  ],
  "rarity": 1,
  "evolvesTo": "kadabra"
 },
 {
  "id": "kadabra",
  "pid": 64,
  "name": "Kadabra",
  "types": [
   "Psychic"
  ],
  "rarity": 2,
  "evolvesTo": "alakazam"
 },
 {
  "id": "alakazam",
  "pid": 65,
  "name": "Alakazam",
  "types": [
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "machop",
  "pid": 66,
  "name": "Machop",
  "types": [
   "Fighting"
  ],
  "rarity": 1,
  "evolvesTo": "machoke"
 },
 {
  "id": "machoke",
  "pid": 67,
  "name": "Machoke",
  "types": [
   "Fighting"
  ],
  "rarity": 2,
  "evolvesTo": "machamp"
 },
 {
  "id": "machamp",
  "pid": 68,
  "name": "Machamp",
  "types": [
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "bellsprout",
  "pid": 69,
  "name": "Bellsprout",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "weepinbell"
 },
 {
  "id": "weepinbell",
  "pid": 70,
  "name": "Weepinbell",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "victreebel"
 },
 {
  "id": "victreebel",
  "pid": 71,
  "name": "Victreebel",
  "types": [
   "Grass",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "tentacool",
  "pid": 72,
  "name": "Tentacool",
  "types": [
   "Water",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "tentacruel"
 },
 {
  "id": "tentacruel",
  "pid": 73,
  "name": "Tentacruel",
  "types": [
   "Water",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "geodude",
  "pid": 74,
  "name": "Geodude",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "graveler"
 },
 {
  "id": "graveler",
  "pid": 75,
  "name": "Graveler",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 2,
  "evolvesTo": "golem"
 },
 {
  "id": "golem",
  "pid": 76,
  "name": "Golem",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "ponyta",
  "pid": 77,
  "name": "Ponyta",
  "types": [
   "Fire"
  ],
  "rarity": 2,
  "evolvesTo": "rapidash"
 },
 {
  "id": "rapidash",
  "pid": 78,
  "name": "Rapidash",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "slowpoke",
  "pid": 79,
  "name": "Slowpoke",
  "types": [
   "Water",
   "Psychic"
  ],
  "rarity": 1,
  "evolvesTo": "slowbro"
 },
 {
  "id": "slowbro",
  "pid": 80,
  "name": "Slowbro",
  "types": [
   "Water",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "magnemite",
  "pid": 81,
  "name": "Magnemite",
  "types": [
   "Electric",
   "Steel"
  ],
  "rarity": 1,
  "evolvesTo": "magneton"
 },
 {
  "id": "magneton",
  "pid": 82,
  "name": "Magneton",
  "types": [
   "Electric",
   "Steel"
  ],
  "rarity": 3
 },
 {
  "id": "farfetchd",
  "pid": 83,
  "name": "Farfetch’d",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "doduo",
  "pid": 84,
  "name": "Doduo",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "dodrio"
 },
 {
  "id": "dodrio",
  "pid": 85,
  "name": "Dodrio",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "seel",
  "pid": 86,
  "name": "Seel",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "dewgong"
 },
 {
  "id": "dewgong",
  "pid": 87,
  "name": "Dewgong",
  "types": [
   "Water",
   "Ice"
  ],
  "rarity": 3
 },
 {
  "id": "grimer",
  "pid": 88,
  "name": "Grimer",
  "types": [
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "muk"
 },
 {
  "id": "muk",
  "pid": 89,
  "name": "Muk",
  "types": [
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "shellder",
  "pid": 90,
  "name": "Shellder",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "cloyster"
 },
 {
  "id": "cloyster",
  "pid": 91,
  "name": "Cloyster",
  "types": [
   "Water",
   "Ice"
  ],
  "rarity": 3
 },
 {
  "id": "gastly",
  "pid": 92,
  "name": "Gastly",
  "types": [
   "Ghost",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "haunter"
 },
 {
  "id": "haunter",
  "pid": 93,
  "name": "Haunter",
  "types": [
   "Ghost",
   "Poison"
  ],
  "rarity": 2,
  "evolvesTo": "gengar"
 },
 {
  "id": "gengar",
  "pid": 94,
  "name": "Gengar",
  "types": [
   "Ghost",
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "onix",
  "pid": 95,
  "name": "Onix",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "steelix"
 },
 {
  "id": "drowzee",
  "pid": 96,
  "name": "Drowzee",
  "types": [
   "Psychic"
  ],
  "rarity": 1,
  "evolvesTo": "hypno"
 },
 {
  "id": "hypno",
  "pid": 97,
  "name": "Hypno",
  "types": [
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "krabby",
  "pid": 98,
  "name": "Krabby",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "kingler"
 },
 {
  "id": "kingler",
  "pid": 99,
  "name": "Kingler",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "voltorb",
  "pid": 100,
  "name": "Voltorb",
  "types": [
   "Electric"
  ],
  "rarity": 1,
  "evolvesTo": "electrode"
 },
 {
  "id": "electrode",
  "pid": 101,
  "name": "Electrode",
  "types": [
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "exeggcute",
  "pid": 102,
  "name": "Exeggcute",
  "types": [
   "Grass",
   "Psychic"
  ],
  "rarity": 1,
  "evolvesTo": "exeggutor"
 },
 {
  "id": "exeggutor",
  "pid": 103,
  "name": "Exeggutor",
  "types": [
   "Grass",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "cubone",
  "pid": 104,
  "name": "Cubone",
  "types": [
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "marowak"
 },
 {
  "id": "marowak",
  "pid": 105,
  "name": "Marowak",
  "types": [
   "Ground"
  ],
  "rarity": 2
 },
 {
  "id": "hitmonlee",
  "pid": 106,
  "name": "Hitmonlee",
  "types": [
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "hitmonchan",
  "pid": 107,
  "name": "Hitmonchan",
  "types": [
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "lickitung",
  "pid": 108,
  "name": "Lickitung",
  "types": [
   "Normal"
  ],
  "rarity": 1
 },
 {
  "id": "koffing",
  "pid": 109,
  "name": "Koffing",
  "types": [
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "weezing"
 },
 {
  "id": "weezing",
  "pid": 110,
  "name": "Weezing",
  "types": [
   "Poison"
  ],
  "rarity": 3
 },
 {
  "id": "rhyhorn",
  "pid": 111,
  "name": "Rhyhorn",
  "types": [
   "Ground",
   "Rock"
  ],
  "rarity": 1,
  "evolvesTo": "rhydon"
 },
 {
  "id": "rhydon",
  "pid": 112,
  "name": "Rhydon",
  "types": [
   "Ground",
   "Rock"
  ],
  "rarity": 3
 },
 {
  "id": "chansey",
  "pid": 113,
  "name": "Chansey",
  "types": [
   "Normal"
  ],
  "rarity": 3,
  "evolvesTo": "blissey"
 },
 {
  "id": "tangela",
  "pid": 114,
  "name": "Tangela",
  "types": [
   "Grass"
  ],
  "rarity": 2
 },
 {
  "id": "kangaskhan",
  "pid": 115,
  "name": "Kangaskhan",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "horsea",
  "pid": 116,
  "name": "Horsea",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "seadra"
 },
 {
  "id": "seadra",
  "pid": 117,
  "name": "Seadra",
  "types": [
   "Water"
  ],
  "rarity": 3,
  "evolvesTo": "kingdra"
 },
 {
  "id": "goldeen",
  "pid": 118,
  "name": "Goldeen",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "seaking"
 },
 {
  "id": "seaking",
  "pid": 119,
  "name": "Seaking",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "staryu",
  "pid": 120,
  "name": "Staryu",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "starmie"
 },
 {
  "id": "starmie",
  "pid": 121,
  "name": "Starmie",
  "types": [
   "Water",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "mr-mime",
  "pid": 122,
  "name": "Mr. Mime",
  "types": [
   "Psychic",
   "Fairy"
  ],
  "rarity": 3
 },
 {
  "id": "scyther",
  "pid": 123,
  "name": "Scyther",
  "types": [
   "Bug",
   "Flying"
  ],
  "rarity": 2,
  "evolvesTo": "scizor"
 },
 {
  "id": "jynx",
  "pid": 124,
  "name": "Jynx",
  "types": [
   "Ice",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "electabuzz",
  "pid": 125,
  "name": "Electabuzz",
  "types": [
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "magmar",
  "pid": 126,
  "name": "Magmar",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "pinsir",
  "pid": 127,
  "name": "Pinsir",
  "types": [
   "Bug"
  ],
  "rarity": 3
 },
 {
  "id": "tauros",
  "pid": 128,
  "name": "Tauros",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "magikarp",
  "pid": 129,
  "name": "Magikarp",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "gyarados"
 },
 {
  "id": "gyarados",
  "pid": 130,
  "name": "Gyarados",
  "types": [
   "Water",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "lapras",
  "pid": 131,
  "name": "Lapras",
  "types": [
   "Water",
   "Ice"
  ],
  "rarity": 3
 },
 {
  "id": "ditto",
  "pid": 132,
  "name": "Ditto",
  "types": [
   "Normal"
  ],
  "rarity": 2
 },
 {
  "id": "eevee",
  "pid": 133,
  "name": "Eevee",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "vaporeon"
 },
 {
  "id": "vaporeon",
  "pid": 134,
  "name": "Vaporeon",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "jolteon",
  "pid": 135,
  "name": "Jolteon",
  "types": [
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "flareon",
  "pid": 136,
  "name": "Flareon",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "porygon",
  "pid": 137,
  "name": "Porygon",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "porygon2"
 },
 {
  "id": "omanyte",
  "pid": 138,
  "name": "Omanyte",
  "types": [
   "Rock",
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "omastar"
 },
 {
  "id": "omastar",
  "pid": 139,
  "name": "Omastar",
  "types": [
   "Rock",
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "kabuto",
  "pid": 140,
  "name": "Kabuto",
  "types": [
   "Rock",
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "kabutops"
 },
 {
  "id": "kabutops",
  "pid": 141,
  "name": "Kabutops",
  "types": [
   "Rock",
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "aerodactyl",
  "pid": 142,
  "name": "Aerodactyl",
  "types": [
   "Rock",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "snorlax",
  "pid": 143,
  "name": "Snorlax",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "articuno",
  "pid": 144,
  "name": "Articuno",
  "types": [
   "Ice",
   "Flying"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "zapdos",
  "pid": 145,
  "name": "Zapdos",
  "types": [
   "Electric",
   "Flying"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "moltres",
  "pid": 146,
  "name": "Moltres",
  "types": [
   "Fire",
   "Flying"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "dratini",
  "pid": 147,
  "name": "Dratini",
  "types": [
   "Dragon"
  ],
  "rarity": 1,
  "evolvesTo": "dragonair"
 },
 {
  "id": "dragonair",
  "pid": 148,
  "name": "Dragonair",
  "types": [
   "Dragon"
  ],
  "rarity": 2,
  "evolvesTo": "dragonite"
 },
 {
  "id": "dragonite",
  "pid": 149,
  "name": "Dragonite",
  "types": [
   "Dragon",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "mewtwo",
  "pid": 150,
  "name": "Mewtwo",
  "types": [
   "Psychic"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "mew",
  "pid": 151,
  "name": "Mew",
  "types": [
   "Psychic"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "chikorita",
  "pid": 152,
  "name": "Chikorita",
  "types": [
   "Grass"
  ],
  "rarity": 1,
  "evolvesTo": "bayleef"
 },
 {
  "id": "bayleef",
  "pid": 153,
  "name": "Bayleef",
  "types": [
   "Grass"
  ],
  "rarity": 2,
  "evolvesTo": "meganium"
 },
 {
  "id": "meganium",
  "pid": 154,
  "name": "Meganium",
  "types": [
   "Grass"
  ],
  "rarity": 3
 },
 {
  "id": "cyndaquil",
  "pid": 155,
  "name": "Cyndaquil",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "quilava"
 },
 {
  "id": "quilava",
  "pid": 156,
  "name": "Quilava",
  "types": [
   "Fire"
  ],
  "rarity": 2,
  "evolvesTo": "typhlosion"
 },
 {
  "id": "typhlosion",
  "pid": 157,
  "name": "Typhlosion",
  "types": [
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "totodile",
  "pid": 158,
  "name": "Totodile",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "croconaw"
 },
 {
  "id": "croconaw",
  "pid": 159,
  "name": "Croconaw",
  "types": [
   "Water"
  ],
  "rarity": 2,
  "evolvesTo": "feraligatr"
 },
 {
  "id": "feraligatr",
  "pid": 160,
  "name": "Feraligatr",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "sentret",
  "pid": 161,
  "name": "Sentret",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "furret"
 },
 {
  "id": "furret",
  "pid": 162,
  "name": "Furret",
  "types": [
   "Normal"
  ],
  "rarity": 2
 },
 {
  "id": "hoothoot",
  "pid": 163,
  "name": "Hoothoot",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "noctowl"
 },
 {
  "id": "noctowl",
  "pid": 164,
  "name": "Noctowl",
  "types": [
   "Normal",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "ledyba",
  "pid": 165,
  "name": "Ledyba",
  "types": [
   "Bug",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "ledian"
 },
 {
  "id": "ledian",
  "pid": 166,
  "name": "Ledian",
  "types": [
   "Bug",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "spinarak",
  "pid": 167,
  "name": "Spinarak",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 1,
  "evolvesTo": "ariados"
 },
 {
  "id": "ariados",
  "pid": 168,
  "name": "Ariados",
  "types": [
   "Bug",
   "Poison"
  ],
  "rarity": 2
 },
 {
  "id": "crobat",
  "pid": 169,
  "name": "Crobat",
  "types": [
   "Poison",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "chinchou",
  "pid": 170,
  "name": "Chinchou",
  "types": [
   "Water",
   "Electric"
  ],
  "rarity": 1,
  "evolvesTo": "lanturn"
 },
 {
  "id": "lanturn",
  "pid": 171,
  "name": "Lanturn",
  "types": [
   "Water",
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "pichu",
  "pid": 172,
  "name": "Pichu",
  "types": [
   "Electric"
  ],
  "rarity": 1,
  "evolvesTo": "pikachu"
 },
 {
  "id": "cleffa",
  "pid": 173,
  "name": "Cleffa",
  "types": [
   "Fairy"
  ],
  "rarity": 1,
  "evolvesTo": "clefairy"
 },
 {
  "id": "igglybuff",
  "pid": 174,
  "name": "Igglybuff",
  "types": [
   "Normal",
   "Fairy"
  ],
  "rarity": 1,
  "evolvesTo": "jigglypuff"
 },
 {
  "id": "togepi",
  "pid": 175,
  "name": "Togepi",
  "types": [
   "Fairy"
  ],
  "rarity": 1,
  "evolvesTo": "togetic"
 },
 {
  "id": "togetic",
  "pid": 176,
  "name": "Togetic",
  "types": [
   "Fairy",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "natu",
  "pid": 177,
  "name": "Natu",
  "types": [
   "Psychic",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "xatu"
 },
 {
  "id": "xatu",
  "pid": 178,
  "name": "Xatu",
  "types": [
   "Psychic",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "mareep",
  "pid": 179,
  "name": "Mareep",
  "types": [
   "Electric"
  ],
  "rarity": 1,
  "evolvesTo": "flaaffy"
 },
 {
  "id": "flaaffy",
  "pid": 180,
  "name": "Flaaffy",
  "types": [
   "Electric"
  ],
  "rarity": 2,
  "evolvesTo": "ampharos"
 },
 {
  "id": "ampharos",
  "pid": 181,
  "name": "Ampharos",
  "types": [
   "Electric"
  ],
  "rarity": 3
 },
 {
  "id": "bellossom",
  "pid": 182,
  "name": "Bellossom",
  "types": [
   "Grass"
  ],
  "rarity": 3
 },
 {
  "id": "marill",
  "pid": 183,
  "name": "Marill",
  "types": [
   "Water",
   "Fairy"
  ],
  "rarity": 2,
  "evolvesTo": "azumarill"
 },
 {
  "id": "azumarill",
  "pid": 184,
  "name": "Azumarill",
  "types": [
   "Water",
   "Fairy"
  ],
  "rarity": 3
 },
 {
  "id": "sudowoodo",
  "pid": 185,
  "name": "Sudowoodo",
  "types": [
   "Rock"
  ],
  "rarity": 2
 },
 {
  "id": "politoed",
  "pid": 186,
  "name": "Politoed",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "hoppip",
  "pid": 187,
  "name": "Hoppip",
  "types": [
   "Grass",
   "Flying"
  ],
  "rarity": 1,
  "evolvesTo": "skiploom"
 },
 {
  "id": "skiploom",
  "pid": 188,
  "name": "Skiploom",
  "types": [
   "Grass",
   "Flying"
  ],
  "rarity": 2,
  "evolvesTo": "jumpluff"
 },
 {
  "id": "jumpluff",
  "pid": 189,
  "name": "Jumpluff",
  "types": [
   "Grass",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "aipom",
  "pid": 190,
  "name": "Aipom",
  "types": [
   "Normal"
  ],
  "rarity": 1
 },
 {
  "id": "sunkern",
  "pid": 191,
  "name": "Sunkern",
  "types": [
   "Grass"
  ],
  "rarity": 1,
  "evolvesTo": "sunflora"
 },
 {
  "id": "sunflora",
  "pid": 192,
  "name": "Sunflora",
  "types": [
   "Grass"
  ],
  "rarity": 2
 },
 {
  "id": "yanma",
  "pid": 193,
  "name": "Yanma",
  "types": [
   "Bug",
   "Flying"
  ],
  "rarity": 1
 },
 {
  "id": "wooper",
  "pid": 194,
  "name": "Wooper",
  "types": [
   "Water",
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "quagsire"
 },
 {
  "id": "quagsire",
  "pid": 195,
  "name": "Quagsire",
  "types": [
   "Water",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "espeon",
  "pid": 196,
  "name": "Espeon",
  "types": [
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "umbreon",
  "pid": 197,
  "name": "Umbreon",
  "types": [
   "Dark"
  ],
  "rarity": 3
 },
 {
  "id": "murkrow",
  "pid": 198,
  "name": "Murkrow",
  "types": [
   "Dark",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "slowking",
  "pid": 199,
  "name": "Slowking",
  "types": [
   "Water",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "misdreavus",
  "pid": 200,
  "name": "Misdreavus",
  "types": [
   "Ghost"
  ],
  "rarity": 2
 },
 {
  "id": "unown",
  "pid": 201,
  "name": "Unown",
  "types": [
   "Psychic"
  ],
  "rarity": 2
 },
 {
  "id": "wobbuffet",
  "pid": 202,
  "name": "Wobbuffet",
  "types": [
   "Psychic"
  ],
  "rarity": 2
 },
 {
  "id": "girafarig",
  "pid": 203,
  "name": "Girafarig",
  "types": [
   "Normal",
   "Psychic"
  ],
  "rarity": 3
 },
 {
  "id": "pineco",
  "pid": 204,
  "name": "Pineco",
  "types": [
   "Bug"
  ],
  "rarity": 1,
  "evolvesTo": "forretress"
 },
 {
  "id": "forretress",
  "pid": 205,
  "name": "Forretress",
  "types": [
   "Bug",
   "Steel"
  ],
  "rarity": 3
 },
 {
  "id": "dunsparce",
  "pid": 206,
  "name": "Dunsparce",
  "types": [
   "Normal"
  ],
  "rarity": 2
 },
 {
  "id": "gligar",
  "pid": 207,
  "name": "Gligar",
  "types": [
   "Ground",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "steelix",
  "pid": 208,
  "name": "Steelix",
  "types": [
   "Steel",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "snubbull",
  "pid": 209,
  "name": "Snubbull",
  "types": [
   "Fairy"
  ],
  "rarity": 1,
  "evolvesTo": "granbull"
 },
 {
  "id": "granbull",
  "pid": 210,
  "name": "Granbull",
  "types": [
   "Fairy"
  ],
  "rarity": 3
 },
 {
  "id": "qwilfish",
  "pid": 211,
  "name": "Qwilfish",
  "types": [
   "Water",
   "Poison"
  ],
  "rarity": 2
 },
 {
  "id": "scizor",
  "pid": 212,
  "name": "Scizor",
  "types": [
   "Bug",
   "Steel"
  ],
  "rarity": 3
 },
 {
  "id": "shuckle",
  "pid": 213,
  "name": "Shuckle",
  "types": [
   "Bug",
   "Rock"
  ],
  "rarity": 3
 },
 {
  "id": "heracross",
  "pid": 214,
  "name": "Heracross",
  "types": [
   "Bug",
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "sneasel",
  "pid": 215,
  "name": "Sneasel",
  "types": [
   "Dark",
   "Ice"
  ],
  "rarity": 2
 },
 {
  "id": "teddiursa",
  "pid": 216,
  "name": "Teddiursa",
  "types": [
   "Normal"
  ],
  "rarity": 1,
  "evolvesTo": "ursaring"
 },
 {
  "id": "ursaring",
  "pid": 217,
  "name": "Ursaring",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "slugma",
  "pid": 218,
  "name": "Slugma",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "magcargo"
 },
 {
  "id": "magcargo",
  "pid": 219,
  "name": "Magcargo",
  "types": [
   "Fire",
   "Rock"
  ],
  "rarity": 3
 },
 {
  "id": "swinub",
  "pid": 220,
  "name": "Swinub",
  "types": [
   "Ice",
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "piloswine"
 },
 {
  "id": "piloswine",
  "pid": 221,
  "name": "Piloswine",
  "types": [
   "Ice",
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "corsola",
  "pid": 222,
  "name": "Corsola",
  "types": [
   "Water",
   "Rock"
  ],
  "rarity": 2
 },
 {
  "id": "remoraid",
  "pid": 223,
  "name": "Remoraid",
  "types": [
   "Water"
  ],
  "rarity": 1,
  "evolvesTo": "octillery"
 },
 {
  "id": "octillery",
  "pid": 224,
  "name": "Octillery",
  "types": [
   "Water"
  ],
  "rarity": 3
 },
 {
  "id": "delibird",
  "pid": 225,
  "name": "Delibird",
  "types": [
   "Ice",
   "Flying"
  ],
  "rarity": 2
 },
 {
  "id": "mantine",
  "pid": 226,
  "name": "Mantine",
  "types": [
   "Water",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "skarmory",
  "pid": 227,
  "name": "Skarmory",
  "types": [
   "Steel",
   "Flying"
  ],
  "rarity": 3
 },
 {
  "id": "houndour",
  "pid": 228,
  "name": "Houndour",
  "types": [
   "Dark",
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "houndoom"
 },
 {
  "id": "houndoom",
  "pid": 229,
  "name": "Houndoom",
  "types": [
   "Dark",
   "Fire"
  ],
  "rarity": 3
 },
 {
  "id": "kingdra",
  "pid": 230,
  "name": "Kingdra",
  "types": [
   "Water",
   "Dragon"
  ],
  "rarity": 3
 },
 {
  "id": "phanpy",
  "pid": 231,
  "name": "Phanpy",
  "types": [
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "donphan"
 },
 {
  "id": "donphan",
  "pid": 232,
  "name": "Donphan",
  "types": [
   "Ground"
  ],
  "rarity": 3
 },
 {
  "id": "porygon2",
  "pid": 233,
  "name": "Porygon2",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "stantler",
  "pid": 234,
  "name": "Stantler",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "smeargle",
  "pid": 235,
  "name": "Smeargle",
  "types": [
   "Normal"
  ],
  "rarity": 2
 },
 {
  "id": "tyrogue",
  "pid": 236,
  "name": "Tyrogue",
  "types": [
   "Fighting"
  ],
  "rarity": 1,
  "evolvesTo": "hitmonlee"
 },
 {
  "id": "hitmontop",
  "pid": 237,
  "name": "Hitmontop",
  "types": [
   "Fighting"
  ],
  "rarity": 3
 },
 {
  "id": "smoochum",
  "pid": 238,
  "name": "Smoochum",
  "types": [
   "Ice",
   "Psychic"
  ],
  "rarity": 1,
  "evolvesTo": "jynx"
 },
 {
  "id": "elekid",
  "pid": 239,
  "name": "Elekid",
  "types": [
   "Electric"
  ],
  "rarity": 1,
  "evolvesTo": "electabuzz"
 },
 {
  "id": "magby",
  "pid": 240,
  "name": "Magby",
  "types": [
   "Fire"
  ],
  "rarity": 1,
  "evolvesTo": "magmar"
 },
 {
  "id": "miltank",
  "pid": 241,
  "name": "Miltank",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "blissey",
  "pid": 242,
  "name": "Blissey",
  "types": [
   "Normal"
  ],
  "rarity": 3
 },
 {
  "id": "raikou",
  "pid": 243,
  "name": "Raikou",
  "types": [
   "Electric"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "entei",
  "pid": 244,
  "name": "Entei",
  "types": [
   "Fire"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "suicune",
  "pid": 245,
  "name": "Suicune",
  "types": [
   "Water"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "larvitar",
  "pid": 246,
  "name": "Larvitar",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 1,
  "evolvesTo": "pupitar"
 },
 {
  "id": "pupitar",
  "pid": 247,
  "name": "Pupitar",
  "types": [
   "Rock",
   "Ground"
  ],
  "rarity": 2,
  "evolvesTo": "tyranitar"
 },
 {
  "id": "tyranitar",
  "pid": 248,
  "name": "Tyranitar",
  "types": [
   "Rock",
   "Dark"
  ],
  "rarity": 3
 },
 {
  "id": "lugia",
  "pid": 249,
  "name": "Lugia",
  "types": [
   "Psychic",
   "Flying"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "ho-oh",
  "pid": 250,
  "name": "Ho-Oh",
  "types": [
   "Fire",
   "Flying"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 },
 {
  "id": "celebi",
  "pid": 251,
  "name": "Celebi",
  "types": [
   "Psychic",
   "Grass"
  ],
  "rarity": 3,
  "req": {
   "minStreak": 7,
   "minSessions": 100
  }
 }
];
